export interface Countries {
    id: string;
    name: string;
    nameWithCode: string;
    code: string;
    logo: string;
}
export const countryList: Countries[] = [
    { id: "", name: 'Algeria', nameWithCode: 'Algeria (+213)', code: '213', logo: "" },
    { id: "", name: 'Andorra', nameWithCode: 'Andorra (+376)', code: '376', logo: "" },
    { id: "", name: 'Angola', nameWithCode: 'Angola (+244)', code: '244', logo: "" },
    { id: "", name: 'Anguilla', nameWithCode: 'Anguilla (+1264)', code: '1264', logo: "" },
    { id: "", name: 'Antigua &amp; Barbuda', nameWithCode: 'Antigua &amp; Barbuda (+1268)', code: '1268', logo: "" },
    { id: "", name: 'Argentina', nameWithCode: 'Argentina (+54)', code: '54', logo: "" },
    { id: "", name: 'Armenia', nameWithCode: 'Armenia (+374)', code: '374', logo: "" },
    { id: "", name: 'Aruba', nameWithCode: 'Aruba (+297)', code: '297', logo: "" },
    { id: "", name: 'Australia', nameWithCode: 'Australia (+61)', code: '61', logo: "" },
    { id: "", name: 'Austria', nameWithCode: 'Austria (+43)', code: '43', logo: "" },
    { id: "", name: 'Azerbaijan', nameWithCode: 'Azerbaijan (+994)', code: '994', logo: "" },
    { id: "", name: 'Bahamas', nameWithCode: 'Bahamas (+1242)', code: '1242', logo: "" },
    { id: "", name: 'Bahrain', nameWithCode: 'Bahrain (+973)', code: '973', logo: "" },
    { id: "", name: 'Bangladesh', nameWithCode: 'Bangladesh (+880)', code: '880', logo: "" },
    { id: "", name: 'Barbados', nameWithCode: 'Barbados (+1246)', code: '1246', logo: "" },
    { id: "", name: 'Belarus', nameWithCode: 'Belarus (+375)', code: '375', logo: "" },
    { id: "", name: 'Belgium', nameWithCode: 'Belgium (+32)', code: '32', logo: "" },
    { id: "", name: 'Belize', nameWithCode: 'Belize (+501)', code: '501', logo: "" },
    { id: "", name: 'Benin', nameWithCode: 'Benin (+229)', code: '229', logo: "" },
    { id: "", name: 'Bermuda', nameWithCode: 'Bermuda (+1441)', code: '1441', logo: "" },
    { id: "", name: 'Bhutan', nameWithCode: 'Bhutan (+975)', code: '975', logo: "" },
    { id: "", name: 'Bolivia', nameWithCode: 'Bolivia (+591)', code: '591', logo: "" },
    { id: "", name: 'Bosnia Herzegovina', nameWithCode: 'Bosnia Herzegovina (+387)', code: '387', logo: "" },
    { id: "", name: 'Botswana', nameWithCode: 'Botswana (+267)', code: '267', logo: "" },
    { id: "", name: 'Brazil', nameWithCode: 'Brazil (+55)', code: '55', logo: "" },
    { id: "", name: 'Brunei', nameWithCode: 'Brunei (+673)', code: '673', logo: "" },
    { id: "", name: 'Bulgaria', nameWithCode: 'Bulgaria (+359)', code: '359', logo: "" },
    { id: "", name: 'Burkina Faso', nameWithCode: 'Burkina Faso (+226)', code: '226', logo: "" },
    { id: "", name: 'Burundi', nameWithCode: 'Burundi (+257)', code: '257', logo: "" },
    { id: "", name: 'Cambodia', nameWithCode: 'Cambodia (+855)', code: '855', logo: "" },
    { id: "", name: 'Cameroon', nameWithCode: 'Cameroon (+237)', code: '237', logo: "" },
    { id: "", name: 'Canada', nameWithCode: 'Canada (+1)', code: '1', logo: "" },
    { id: "", name: 'Cape Verde Islands', nameWithCode: 'Cape Verde Islands (+238)', code: '238', logo: "" },
    { id: "", name: 'Cayman Islands', nameWithCode: 'Cayman Islands (+1345)', code: '1345', logo: "" },
    { id: "", name: 'Central African Republic', nameWithCode: 'Central African Republic (+236)', code: '236', logo: "" },
    { id: "", name: 'Chile', nameWithCode: 'Chile (+56)', code: '56', logo: "" },
    { id: "", name: 'China', nameWithCode: 'China (+86)', code: '86', logo: "" },
    { id: "", name: 'Colombia', nameWithCode: 'Colombia (+57)', code: '57', logo: "" },
    { id: "", name: 'Comoros', nameWithCode: 'Comoros (+269)', code: '269', logo: "" },
    { id: "", name: 'Congo', nameWithCode: 'Congo (+242)', code: '242', logo: "" },
    { id: "", name: 'Cook Islands', nameWithCode: 'Cook Islands (+682)', code: '682', logo: "" },
    { id: "", name: 'Costa Rica', nameWithCode: 'Costa Rica (+506)', code: '506', logo: "" },
    { id: "", name: 'Croatia', nameWithCode: 'Croatia (+385)', code: '385', logo: "" },
    { id: "", name: 'Cuba', nameWithCode: 'Cuba (+53)', code: '53', logo: "" },
    { id: "", name: 'Cyprus North', nameWithCode: 'Cyprus North (+90392)', code: '90392', logo: "" },
    { id: "", name: 'Cyprus South', nameWithCode: 'Cyprus South (+357)', code: '357', logo: "" },
    { id: "", name: 'Czech Republic', nameWithCode: 'Czech Republic (+42)', code: '42', logo: "" },
    { id: "", name: 'Denmark', nameWithCode: 'Denmark (+45)', code: '45', logo: "" },
    { id: "", name: 'Djibouti', nameWithCode: 'Djibouti (+253)', code: '253', logo: "" },
    { id: "", name: 'Dominica', nameWithCode: 'Dominica (+1809)', code: '1809', logo: "" },
    { id: "", name: 'Dominican Republic', nameWithCode: 'Dominican Republic (+1809)', code: '1809', logo: "" },
    { id: "", name: 'Ecuador', nameWithCode: 'Ecuador (+593)', code: '593', logo: "" },
    { id: "", name: 'Egypt', nameWithCode: 'Egypt (+20)', code: '20', logo: "" },
    { id: "", name: 'El Salvador', nameWithCode: 'El Salvador (+503)', code: '503', logo: "" },
    { id: "", name: 'Equatorial Guinea', nameWithCode: 'Equatorial Guinea (+240)', code: '240', logo: "" },
    { id: "", name: 'Eritrea', nameWithCode: 'Eritrea (+291)', code: '291', logo: "" },
    { id: "", name: 'Estonia', nameWithCode: 'Estonia (+372)', code: '372', logo: "" },
    { id: "", name: 'Ethiopia', nameWithCode: 'Ethiopia (+251)', code: '251', logo: "" },
    { id: "", name: 'Falkland Islands', nameWithCode: 'Falkland Islands (+500)', code: '500', logo: "" },
    { id: "", name: 'Faroe Islands', nameWithCode: 'Faroe Islands (+298)', code: '298', logo: "" },
    { id: "", name: 'Fiji', nameWithCode: 'Fiji (+679)', code: '679', logo: "" },
    { id: "", name: 'Finland', nameWithCode: 'Finland (+358)', code: '358', logo: "" },
    { id: "", name: 'France', nameWithCode: 'France (+33)', code: '33', logo: "" },
    { id: "", name: 'French Guiana', nameWithCode: 'French Guiana (+594)', code: '594', logo: "" },
    { id: "", name: 'French Polynesia', nameWithCode: 'French Polynesia (+689)', code: '689', logo: "" },
    { id: "", name: 'Gabon', nameWithCode: 'Gabon (+241)', code: '241', logo: "" },
    { id: "", name: 'Gambia', nameWithCode: 'Gambia (+220)', code: '220', logo: "" },
    { id: "", name: 'Georgia', nameWithCode: 'Georgia (+7880)', code: '7880', logo: "" },
    { id: "", name: 'Germany', nameWithCode: 'Germany (+49)', code: '49', logo: "" },
    { id: "", name: 'Ghana', nameWithCode: 'Ghana (+233)', code: '233', logo: "" },
    { id: "", name: 'Gibraltar', nameWithCode: 'Gibraltar (+350)', code: '350', logo: "" },
    { id: "", name: 'Greece', nameWithCode: 'Greece (+30)', code: '30', logo: "" },
    { id: "", name: 'Greenland', nameWithCode: 'Greenland (+299)', code: '299', logo: "" },
    { id: "", name: 'Grenada', nameWithCode: 'Grenada (+1473)', code: '1473', logo: "" },
    { id: "", name: 'Guadeloupe', nameWithCode: 'Guadeloupe (+590)', code: '590', logo: "" },
    { id: "", name: 'Guam', nameWithCode: 'Guam (+671)', code: '671', logo: "" },
    { id: "", name: 'Guatemala', nameWithCode: 'Guatemala (+502)', code: '502', logo: "" },
    { id: "", name: 'Guinea', nameWithCode: 'Guinea (+224)', code: '224', logo: "" },
    { id: "", name: 'Guinea - Bissau', nameWithCode: 'Guinea - Bissau (+245)', code: '245', logo: "" },
    { id: "", name: 'Guyana', nameWithCode: 'Guyana (+592)', code: '592', logo: "" },
    { id: "", name: 'Haiti', nameWithCode: 'Haiti (+509)', code: '509', logo: "" },
    { id: "", name: 'Honduras', nameWithCode: 'Honduras (+504)', code: '504', logo: "" },
    { id: "", name: 'Hong Kong', nameWithCode: 'Hong Kong (+852)', code: '852', logo: "" },
    { id: "", name: 'Hungary', nameWithCode: 'Hungary (+36)', code: '36', logo: "" },
    { id: "", name: 'Iceland', nameWithCode: 'Iceland (+354)', code: '354', logo: "" },
    { id: "", name: 'India', nameWithCode: 'India (+91)', code: '91', logo: "" },
    { id: "", name: 'Indonesia', nameWithCode: 'Indonesia (+62)', code: '62', logo: "" },
    { id: "", name: 'Iran', nameWithCode: 'Iran (+98)', code: '98', logo: "" },
    { id: "", name: 'Iraq', nameWithCode: 'Iraq (+964)', code: '964', logo: "" },
    { id: "", name: 'Ireland', nameWithCode: 'Ireland (+353)', code: '353', logo: "" },
    { id: "", name: 'Israel', nameWithCode: 'Israel (+972)', code: '972', logo: "" },
    { id: "", name: 'Italy', nameWithCode: 'Italy (+39)', code: '39', logo: "" },
    { id: "", name: 'Jamaica', nameWithCode: 'Jamaica (+1876)', code: '1876', logo: "" },
    { id: "", name: 'Japan', nameWithCode: 'Japan (+81)', code: '81', logo: "" },
    { id: "", name: 'Jordan', nameWithCode: 'Jordan (+962)', code: '962', logo: "" },
    { id: "", name: 'Kazakhstan', nameWithCode: 'Kazakhstan (+7)', code: '7', logo: "" },
    { id: "", name: 'Kenya', nameWithCode: 'Kenya (+254)', code: '254', logo: "" },
    { id: "", name: 'Kiribati', nameWithCode: 'Kiribati (+686)', code: '686', logo: "" },
    { id: "", name: 'Korea North', nameWithCode: 'Korea North (+850)', code: '850', logo: "" },
    { id: "", name: 'Korea South', nameWithCode: 'Korea South (+82)', code: '82', logo: "" },
    { id: "", name: 'Kuwait', nameWithCode: 'Kuwait (+965)', code: '965', logo: "" },
    { id: "", name: 'Kyrgyzstan', nameWithCode: 'Kyrgyzstan (+996)', code: '996', logo: "" },
    { id: "", name: 'Laos', nameWithCode: 'Laos (+856)', code: '856', logo: "" },
    { id: "", name: 'Latvia', nameWithCode: 'Latvia (+371)', code: '371', logo: "" },
    { id: "", name: 'Lebanon', nameWithCode: 'Lebanon (+961)', code: '961', logo: "" },
    { id: "", name: 'Lesotho', nameWithCode: 'Lesotho (+266)', code: '266', logo: "" },
    { id: "", name: 'Liberia', nameWithCode: 'Liberia (+231)', code: '231', logo: "" },
    { id: "", name: 'Libya', nameWithCode: 'Libya (+218)', code: '218', logo: "" },
    { id: "", name: 'Liechtenstein', nameWithCode: 'Liechtenstein (+417)', code: '417', logo: "" },
    { id: "", name: 'Lithuania', nameWithCode: 'Lithuania (+370)', code: '370', logo: "" },
    { id: "", name: 'Luxembourg', nameWithCode: 'Luxembourg (+352)', code: '352', logo: "" },
    { id: "", name: 'Macao', nameWithCode: 'Macao (+853)', code: '853', logo: "" },
    { id: "", name: 'Macedonia', nameWithCode: 'Macedonia (+389)', code: '389', logo: "" },
    { id: "", name: 'Madagascar', nameWithCode: 'Madagascar (+261)', code: '261', logo: "" },
    { id: "", name: 'Malawi', nameWithCode: 'Malawi (+265)', code: '265', logo: "" },
    { id: "", name: 'Malaysia', nameWithCode: 'Malaysia (+60)', code: '60', logo: "" },
    { id: "", name: 'Maldives', nameWithCode: 'Maldives (+960)', code: '960', logo: "" },
    { id: "", name: 'Mali', nameWithCode: 'Mali (+223)', code: '223', logo: "" },
    { id: "", name: 'Malta', nameWithCode: 'Malta (+356)', code: '356', logo: "" },
    { id: "", name: 'Marshall Islands', nameWithCode: 'Marshall Islands (+692)', code: '692', logo: "" },
    { id: "", name: 'Martinique', nameWithCode: 'Martinique (+596)', code: '596', logo: "" },
    { id: "", name: 'Mauritania', nameWithCode: 'Mauritania (+222)', code: '222', logo: "" },
    { id: "", name: 'Mayotte', nameWithCode: 'Mayotte (+269)', code: '269', logo: "" },
    { id: "", name: 'Mexico', nameWithCode: 'Mexico (+52)', code: '52', logo: "" },
    { id: "", name: 'Micronesia', nameWithCode: 'Micronesia (+691)', code: '691', logo: "" },
    { id: "", name: 'Moldova', nameWithCode: 'Moldova (+373)', code: '373', logo: "" },
    { id: "", name: 'Monaco', nameWithCode: 'Monaco (+377)', code: '377', logo: "" },
    { id: "", name: 'Mongolia', nameWithCode: 'Mongolia (+976)', code: '976', logo: "" },
    { id: "", name: 'Montserrat', nameWithCode: 'Montserrat (+1664)', code: '1664', logo: "" },
    { id: "", name: 'Morocco', nameWithCode: 'Morocco (+212)', code: '212', logo: "" },
    { id: "", name: 'Mozambique', nameWithCode: 'Mozambique (+258)', code: '258', logo: "" },
    { id: "", name: 'Myanmar', nameWithCode: 'Myanmar (+95)', code: '95', logo: "" },
    { id: "", name: 'Namibia', nameWithCode: 'Namibia (+264)', code: '264', logo: "" },
    { id: "", name: 'Nauru', nameWithCode: 'Nauru (+674)', code: '674', logo: "" },
    { id: "", name: 'Nepal', nameWithCode: 'Nepal (+977)', code: '977', logo: "" },
    { id: "", name: 'Netherlands', nameWithCode: 'Netherlands (+31)', code: '31', logo: "" },
    { id: "", name: 'New Caledonia', nameWithCode: 'New Caledonia (+687)', code: '687', logo: "" },
    { id: "", name: 'New Zealand', nameWithCode: 'New Zealand (+64)', code: '64', logo: "" },
    { id: "", name: 'Nicaragua', nameWithCode: 'Nicaragua (+505)', code: '505', logo: "" },
    { id: "", name: 'Niger', nameWithCode: 'Niger (+227)', code: '227', logo: "" },
    { id: "", name: 'Nigeria', nameWithCode: 'Nigeria (+234)', code: '234', logo: "" },
    { id: "", name: 'Niue', nameWithCode: 'Niue (+683)', code: '683', logo: "" },
    { id: "", name: 'Norfolk Islands', nameWithCode: 'Norfolk Islands (+672)', code: '672', logo: "" },
    { id: "", name: 'Northern Marianas', nameWithCode: 'Northern Marianas (+670)', code: '670', logo: "" },
    { id: "", name: 'Norway', nameWithCode: 'Norway (+47)', code: '47', logo: "" },
    { id: "", name: 'Oman', nameWithCode: 'Oman (+968)', code: '968', logo: "" },
    { id: "", name: 'Pakistan', nameWithCode: 'Pakistan +92', code: '92', logo: "" },
    { id: "", name: 'Palau', nameWithCode: 'Palau (+680)', code: '680', logo: "" },
    { id: "", name: 'Panama', nameWithCode: 'Panama (+507)', code: '507', logo: "" },
    { id: "", name: 'Papua New Guinea', nameWithCode: 'Papua New Guinea (+675)', code: '675', logo: "" },
    { id: "", name: 'Paraguay', nameWithCode: 'Paraguay (+595)', code: '595', logo: "" },
    { id: "", name: 'Peru', nameWithCode: 'Peru (+51)', code: '51', logo: "" },
    { id: "", name: 'Philippines', nameWithCode: 'Philippines (+63)', code: '63', logo: "" },
    { id: "", name: 'Poland', nameWithCode: 'Poland (+48)', code: '48', logo: "" },
    { id: "", name: 'Portugal', nameWithCode: 'Portugal (+351)', code: '351', logo: "" },
    { id: "", name: 'Puerto Rico', nameWithCode: 'Puerto Rico (+1787)', code: '1787', logo: "" },
    { id: "", name: 'Qatar', nameWithCode: 'Qatar (+974)', code: '974', logo: "" },
    { id: "", name: 'Reunion', nameWithCode: 'Reunion (+262)', code: '262', logo: "" },
    { id: "", name: 'Romania', nameWithCode: 'Romania (+40)', code: '40', logo: "" },
    { id: "", name: 'Russia', nameWithCode: 'Russia (+7)', code: '7', logo: "" },
    { id: "", name: 'Rwanda', nameWithCode: 'Rwanda (+250)', code: '250', logo: "" },
    { id: "", name: 'San Marino', nameWithCode: 'San Marino (+378)', code: '378', logo: "" },
    { id: "", name: 'Sao Tome &amp; Principe', nameWithCode: 'Sao Tome &amp; Principe (+239)', code: '239', logo: "" },
    { id: "", name: 'Saudi Arabia', nameWithCode: 'Saudi Arabia (+966)', code: '966', logo: "" },
    { id: "", name: 'Senegal', nameWithCode: 'Senegal (+221)', code: '221', logo: "" },
    { id: "", name: 'Serbia', nameWithCode: 'Serbia (+381)', code: '381', logo: "" },
    { id: "", name: 'Seychelles', nameWithCode: 'Seychelles (+248)', code: '248', logo: "" },
    { id: "", name: 'Sierra Leone', nameWithCode: 'Sierra Leone (+232)', code: '232', logo: "" },
    { id: "", name: 'Singapore', nameWithCode: 'Singapore (+65)', code: '65', logo: "" },
    { id: "", name: 'Slovak Republic', nameWithCode: 'Slovak Republic (+421)', code: '421', logo: "" },
    { id: "", name: 'Slovenia', nameWithCode: 'Slovenia (+386)', code: '386', logo: "" },
    { id: "", name: 'Solomon Islands', nameWithCode: 'Solomon Islands (+677)', code: '677', logo: "" },
    { id: "", name: 'Somalia', nameWithCode: 'Somalia (+252)', code: '252', logo: "" },
    { id: "", name: 'South Africa ', nameWithCode: 'South Africa (+27)', code: '27', logo: "" },
    { id: "", name: 'Spain', nameWithCode: 'Spain (+34)', code: '34', logo: "" },
    { id: "", name: 'Sri Lanka', nameWithCode: 'Sri Lanka (+94)', code: '94', logo: "" },
    { id: "", name: 'St. Helena', nameWithCode: 'St. Helena (+290)', code: '290', logo: "" },
    { id: "", name: 'St. Kitts', nameWithCode: 'St. Kitts (+1869)', code: '1869', logo: "" },
    { id: "", name: 'St. Lucia', nameWithCode: 'St. Lucia (+1758)', code: '1758', logo: "" },
    { id: "", name: 'Sudan', nameWithCode: 'Sudan (+249)', code: '249', logo: "" },
    { id: "", name: 'Suriname', nameWithCode: 'Suriname (+597)', code: '597', logo: "" },
    { id: "", name: 'Swaziland', nameWithCode: 'Swaziland (+268)', code: '268', logo: "" },
    { id: "", name: 'Sweden', nameWithCode: 'Sweden (+46)', code: '46', logo: "" },
    { id: "", name: 'Switzerland', nameWithCode: 'Switzerland (+41)', code: '41', logo: "" },
    { id: "", name: 'Syria', nameWithCode: 'Syria (+963)', code: '963', logo: "" },
    { id: "", name: 'Taiwan', nameWithCode: 'Taiwan (+886)', code: '886', logo: "" },
    { id: "", name: 'Tajikstan', nameWithCode: 'Tajikstan (+7)', code: '7', logo: "" },
    { id: "", name: 'Thailand', nameWithCode: 'Thailand (+66)', code: '66', logo: "" },
    { id: "", name: 'Togo', nameWithCode: 'Togo (+228)', code: '228', logo: "" },
    { id: "", name: 'Tonga', nameWithCode: 'Tonga (+676)', code: '676', logo: "" },
    { id: "", name: 'Trinidad &amp; Tobago', nameWithCode: 'Trinidad &amp; Tobago (+1868)', code: '1868', logo: "" },
    { id: "", name: 'Tunisia', nameWithCode: 'Tunisia (+216)', code: '216', logo: "" },
    { id: "", name: 'Turkey', nameWithCode: 'Turkey (+90)', code: '90', logo: "" },
    { id: "", name: 'Turkmenistan', nameWithCode: 'Turkmenistan (+7)', code: '7', logo: "" },
    { id: "", name: 'Turkmenistan', nameWithCode: 'Turkmenistan (+993)', code: '993', logo: "" },
    { id: "", name: 'Turks &amp; Caicos Islands ', nameWithCode: 'Turks &amp; Caicos Islands (+1649)', code: '1649', logo: "" },
    { id: "", name: 'Tuvalu', nameWithCode: 'Tuvalu (+688)', code: '688', logo: "" },
    { id: "", name: 'Uganda', nameWithCode: 'Uganda (+256)', code: '256', logo: "" },
    { id: "", name: 'UK', nameWithCode: 'UK (+44)', code: '44', logo: "" },
    { id: "", name: 'Ukraine', nameWithCode: 'Ukraine (+380)', code: '380', logo: "" },
    { id: "", name: 'United Arab Emirates', nameWithCode: 'United Arab Emirates (+971)', code: '971', logo: "" },
    { id: "", name: 'Uruguay', nameWithCode: 'Uruguay (+598)', code: '598', logo: "" },
    { id: "", name: 'USA', nameWithCode: 'USA (+1)', code: '1', logo: "" },
    { id: "", name: 'Uzbekistan', nameWithCode: 'Uzbekistan (+7)', code: '7', logo: "" },
    { id: "", name: 'Vanuatu', nameWithCode: 'Vanuatu (+678)', code: '678', logo: "" },
    { id: "", name: 'Vatican City', nameWithCode: 'Vatican City (+379)', code: '379', logo: "" },
    { id: "", name: 'Venezuela', nameWithCode: 'Venezuela (+58)', code: '58', logo: "" },
    { id: "", name: 'Vietnam', nameWithCode: 'Vietnam (+84)', code: '84', logo: "" },
    { id: "", name: 'Virgin Islands - British', nameWithCode: 'Virgin Islands - British (+1284)', code: '84', logo: "" },
    { id: "", name: 'Virgin Islands - US', nameWithCode: 'Virgin Islands - US (+1340)', code: '84', logo: "" },
    { id: "", name: 'Wallis &amp; Futuna', nameWithCode: 'Wallis &amp; Futuna (+681)', code: '681', logo: "" },
    { id: "", name: 'Yemen (North)', nameWithCode: 'Yemen (North)(+969)', code: '969', logo: "" },
    { id: "", name: 'Yemen (South)', nameWithCode: 'Yemen (South)(+967)', code: '967', logo: "" },
    { id: "", name: 'Zambia', nameWithCode: 'Zambia (+260)', code: '260', logo: "" },
    { id: "", name: 'Zimbabwe', nameWithCode: 'Zimbabwe (+263)', code: '263', logo: "" },
]

